### ISSUE TITLE
load data to db.json time error

### ISSUE THREAD

**Issue by 3Ppaps** [deka108/meas_deka#1]
(env) F:\mathserver>python manage.py --help
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "F:\mathserver\env\lib\site-packages\django\core\management\__init__.py", line 368, in execute_from_command_line
    utility.execute()
  File "F:\mathserver\env\lib\site-packages\django\core\management\__init__.py", line 301, in execute
    parser = CommandParser(usage='%(prog)s subcommand [options] [args]', add_help=False, allow_abbrev=False)
TypeError: __init__() missing 1 required positional argument: 'cmd'

**Comment by deka108** [comment]
Did you try `python manage.py loaddata db.json` ? Also, from the error message it seems that manage.py is requiring an argument, so it should be `python manage.py help` instead.

**Comment by 3Ppaps** [comment]
got this msg
